<?php

namespace IC\ApprovisionnementBundle\Repository;

/**
 * ApproIdentifiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApproIdentifiantRepository extends \Doctrine\ORM\EntityRepository
{
}
