<?php

namespace IC\ApprovisionnementBundle\Repository;

/**
 * ApproComposantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApproComposantRepository extends \Doctrine\ORM\EntityRepository
{
   public function getApproEnCours()
   {
		return $this->createQueryBuilder('ac')
		->select('ac')
		->getQuery()
		->getResult();
   }
}
