<?php

namespace IC\ApprovisionnementBundle\Repository;

/**
 * ApproAutreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApproAutreRepository extends \Doctrine\ORM\EntityRepository
{
}
