<?php

namespace IC\ApprovisionnementBundle\Repository;

/**
 * MoqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoqRepository extends \Doctrine\ORM\EntityRepository
{
}
