<?php

namespace IC\ApprovisionnementBundle\Repository;

/**
 * ProductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListProdEnAttente()
    {
        return $this->createQueryBuilder('p')
        ->join('p.version', 'v')
        ->where('p.etape = 1')
        ->orderBy('p.idLieu', 'ASC')
        ->getQuery()
        ->getResult();        
    }
}
