<?php

namespace IC\AdministrationBundle\Repository;

/**
 * ComposantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComposantRepository extends \Doctrine\ORM\EntityRepository
{
    public function getComposantProduitFini()
    {
        return $this->createQueryBuilder('c')
        ->where('c.idFamille IN(:famille)')
        ->setParameter('famille', array(3,4))
        ->getQuery()
        ->getResult();
    }
    
    public function getComposantPCB()
    {
        return $this->createQueryBuilder('c')
        ->where('c.idFamille IN(:famille)')
        ->setParameter('famille', array(1,2))
        ->getQuery()
        ->getResult();      
    }
}
