<?php

namespace IC\AdministrationBundle\Repository;

/**
 * SousFamilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousFamilleRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getSousFamilleByIdFamille($idFamille)
    {
        return $this->createQueryBuilder('sf')
        ->where('sf.idFamille = :idFamille')
        ->setParameter('idFamille', $idFamille)
        ->getQuery()->getResult();
    }
}
