ic_production:
    resource: "@ICProductionBundle/Resources/config/routing.yml"
    prefix:   /Production

ic_affichage:
    resource: "@ICAffichageBundle/Resources/config/routing.yml"
    prefix:   /Affichage