ic_production_previsionnelle_interne:
    path:     /Previsionelle-Interne
    defaults: { _controller: ICProductionBundle:Previsionnelle:interne }
    
ic_production_previsionnelle_sous_traitant:
    path:     /Previsionelle-SousTraitant-{id}
    defaults: { _controller: ICProductionBundle:Previsionnelle:sousTraitant }
    requirements:
        id: \d{1,10}
        
ic_production_interne_en_cours:
    path:     /Production-en-cours-Interne
    defaults: { _controller: ICProductionBundle:Production:interne }
    
ic_production_sous_traitant_en_cours:
    path:     /Production-en-cours-SousTraitant-{id}
    defaults: { _controller: ICProductionBundle:Production:sousTraitant }
    requirements:
        id: \d{1,10}