ic_production_previsionnelle_interne:
    path:     /Previsionelle-Interne
    defaults: { _controller: ICProductionBundle:Previsionnelle:interne }
    
ic_production_previsionnelle_interne:
    path:     /Previsionelle-SousTraitant-{id}
    defaults: { _controller: ICProductionBundle:Previsionnelle:sousTraitant }
    requirement:
        id: \d
