ic_production_interne:
    path:     /Production-Interne
    defaults: { _controller: ICProductionBundle:Production:interne }
    
ic_production_sous_traitant:
    path:     /Production-SousTraitant-{id}
    defaults: { _controller: ICProductionBundle:Production:sousTraitant }
    requirements:
        id: \d{1,10}

ic_calcul:
    path:     /Calcul{idProducteur}-{idVersion}-{quantite1}-{quantite2}
    defaults:  
        _controller: ICProductionBundle:Production:calcul
        quantite2:   0
    requirements:
        idProducteur: \d{1,10}
        idVersion:    \d{1,10}
        quantite1:    \d{1,10}
        quantite2:    \d{1,10}