ic_production_interne:
    path:     /Production-Interne
    defaults: { _controller: ICProductionBundle:Production:interne }
    
ic_production_sous_traitant:
    path:     /Production-SousTraitant-{id}
    defaults: { _controller: ICProductionBundle:Production:sousTraitant }
    requirements:
        id: \d{1,10}
        