services:
    ic_approvisionnement.calculcomposantprod:
        class: IC\ApprovisionnementBundle\Classes\ICApprovisionnementProduction
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"