<?php

namespace IC\ProductionBundle\Repository;

/**
 * ComposantNomenclatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComposantNomenclatureRepository extends \Doctrine\ORM\EntityRepository
{
	public function getComposantNomenclatureProdInterne($id)
	{
		return $this->createQueryBuilder('nc')
		->join('nc.nomenclature', 'n')
		->join('nc.composant', 'c')
		->join('c.famille', 'f')
		->join('c.sousFamille', 'sf')
		->addSelect('c')
		->where('nc.idNomenclature = :id')
		->setParameter('id', $id)
		->getQuery()
		->getResult();
	}
}
