<?php

namespace IC\ProductionBundle\Repository;

/**
 * ComposantSousTraitantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComposantSousTraitantRepository extends \Doctrine\ORM\EntityRepository
{
}
