<?php

namespace IC\ProductionBundle\Repository;

/**
 * VersionNomenclature
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionNomenclature extends \Doctrine\ORM\EntityRepository
{
    public function getVersion($id)
    {
        return $this->createQueryBuilder('v')
        ->add('orderBy', 'v.version DESC')
        ->where('v.idNomenclature = :id')
        ->setParameter('id', $id)
        ->setMaxResults('1')
        ->getQuery()
        ->getResult();
    }    
}
